name = "transcript-tax-monitor-pro"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".next"

[[pages.redirects]]
from = "/sign-in.html"
to = "/login"
status = 301

[[pages.redirects]]
from = "/about.html"
to = "/about"
status = 301

[[pages.redirects]]
from = "/contact.html"
to = "/contact"
status = 301

[[pages.redirects]]
from = "/index.html"
to = "/"
status = 301
